### ISSUE TITLE
Configuration/deployment instructions

### ISSUE THREAD

**Issue by nyfon** [nemerald-voip/laravel-freeswitch#2]
Hello,
This looks like a nice path! Do you have any deployment/setup instructions?
I installed it and try to run, but can't get beyond login screen...
When csrf token enabled - I get to 419 page expired. I disabled csrf verify and see it's storing session in postgres but returns to the login screen. Please help

**Comment by nemerald-voip** [comment]
Hello, even though the repository is public, it's mainly used by my private clients. This is built on top of FusionPBX. It uses an outdated interface, so I've redesigned many modules using Laravel and created a significant facelift. You are having issues logging in because 2 files need to be modified in Fution to work with Laravel. 
I provide support for FusionPBX and my modified version of it. Suppose you are interested to see the demo. I'll be happy to show you.

**Comment by supremazx** [comment]
I need to see your demo. Please contact me. info@voxidy.co
